_BASE_: [
  '../datasets/DUO_coco.yml',
  '../runtime.yml',
  '_base_/optimizer_36e_xpu.yml',
  '_base_/yolov10_cspdarknet.yml',
  '_base_/yolov10_reader.yml',
]
depth_mult: 1.00
width_mult: 1.00

log_iter: 100
snapshot_epoch: 1
weights: output/yolov10_l_500e_coco/model_final

YOLOv10CSPDarkNet:
  last_stage_ch: 512
  use_c2fcib: true
  use_large_kernel: false

YOLOv10CSPPAN:
  fpn_use_c2fcib: [true, false]
  pan_use_c2fcib: [true, true]
  use_large_kernel: false

save_dir: output/yolov10_l



