metric: COCO
num_classes: 4

TrainDataset:
  name: COCODataSet
  image_dir: DUO_pic/train
  anno_path: DUO_ANN/instances_train.json
  dataset_dir: dataset/DUO
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: DUO_pic/test
  anno_path: DUO_ANN/instances_test.json
  dataset_dir: dataset/DUO
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
