metric: COCO
num_classes: 8

TrainDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: 1.json
  dataset_dir: dataset/Train+A
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: 1.json
  dataset_dir: dataset/TestB
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
